name: XCS224R_CUDA
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - ipython=9.7.0
  - matplotlib=3.10.8
  - moviepy=1.0.3
  - tensorboard=2.20.0
  - ffmpeg=4.2.2
  - pip=25.1
  - pip:
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.9.0+cu126
    - "--find-links https://download.pytorch.org/whl/torchvision/"
    - torchvision==0.24.0+cu126
    - gymnasium[mujoco]==1.2.0
    - tensorflow==2.20.0
    - numpy==2.4.1
    - opencv-python==4.13.0.90
    - swig==4.4.1
    - dm_control==1.0.36
    - hydra-core==1.3.2
    - hydra-submitit-launcher==1.2.0
    - metaworld==3.0.0
